version: '2.4'
services:
    wwwserver:
       build: .
       image: asn/nodewebapp 
       environment:
            PORT: 3000 
       ports:
            - "8080:3000"
       volumes:
            - ./src:/app
       entrypoint: sh -c "rm -fr node_modules ; npm install ; node server.js "
