services:
  sonarserver:
    image: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"

  sonarscanner:
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: "http://sonarserver:9000"
      ## Replace with project login token generated in SonarQube server
      SONAR_TOKEN: "sqp_707ad845875c0ebfce91fdca7a567c2a9832972b"      
    volumes:
      ## Replace ../phpwebapp/html with your project source folder
      - ../phpwebapp/html:/usr/src
      ## Sample project source paths
      #- ./src:/usr/src
      #- /home/user/project:/usr/src
      #- c:/Users/project:/usr/src
#    command: -Dsonar.projectKey="phpwebapp"

