version: '2.4'
services:
  wwwserver:
    build: .
    image: asn/phpwebapp:v1
    ports:
      # Fixed external port for HTTP direct access 
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    # limit resources for testing
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    oom_kill_disable: true #prevent stop containers when they reach their memory limit

    depends_on:
      - mariadb 
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=notesdb
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=secreto
      # Descomentar si hay problemas para incializar la BD de pruebas
      # https://github.com/docker-library/mariadb/issues/160#issuecomment-528393445
#     - MYSQL_INIT_SKIP_TZINFO=1
    ports:
      - 3306:3306
