version: '2.4'
services:
    wwwserver:
       build: .
       image: asn/pythonwebapp:v1 
       environment:
            PORT: 5000 
       ports:
            - "8080:5000"
       volumes:
            - ./src:/app
       entrypoint: sh -c "python server.py "
