http:
  routers:
    front-end:
      rule: "PathPrefix(`/`)"
      service: wwwservers 
  services:
    wwwservers:
      loadBalancer:
        servers:
        - url: http://loadbalancer-wwwserver-1/
        - url: http://loadbalancer-wwwserver-2/
        healthCheck:
