apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-ingress
  annotations:
## Uncomment selected ingress controller
#    kubernetes.io/ingress.class: "nginx"
#    kubernetes.io/ingress.class: "haproxy"
#    kubernetes.io/ingress.class: "gce"  #default in GKE
spec:
  #Default backend service
  defaultBackend:
    service:
      name: testapp
      port:
        number: 80

#  ## Backend services
#  rules:
## - host: localhost 
#    - http:
#        paths:
#        - path: /     
#          pathType: Prefix
#          backend:
#            service:
#              name: testapp 
#              port:
#                number: 80
#        # - path: /app/
#        #   pathType: Prefix
#        #   backend:
#        #     service:
#        #       name: wwwserver 
#        #       port:
#        #         number: 80

