services:
     wwwserver:
          build: .
          image: asn/htmlsite
          environment:
               PORT: 80
          ports:
               - "8080:80"
          volumes:
               - ./html:/var/www/html
          