---
## JR: enable IngressClassName property on ingress resources for selecting ingress controller
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
  name: traefik
  namespace: traefik-controller
## JR: set default ingress controller for ingress resources without ingressclass selection  
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-controller
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: traefik-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: traefik-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: traefik-controller
  labels:
    #app: traefik
    k8s-app: traefik-ingress-lb

spec:
  replicas: 1
  selector:
    matchLabels:
      #app: traefik
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        #app: traefik
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v3.1
          args:
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
            - --accesslog
            - --api
            # enable dashboard
            - --api.insecure
            - --api.dashboard            
            - --api.debug
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik-controller
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-dashboard
  namespace: traefik-controller
spec:
  type: NodePort
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP      
      port: 8080      
      name: admin